#!/bin/bash
# Emits the handover §5 baseline as a markdown table, ready to paste.
#
# Why a script and not a "measure, do not transcribe" instruction: under token pressure a model takes
# the cheapest path, and transcription is cheaper than inventing a measurement command per row. This
# inverts that — measuring is now one call (rules/README.md §Writing for the reader, principle 3).
# Measured precedent: the case-index row said 45 for three sessions while the actual was 48, because
# the row named no command and the previous claim was the cheapest thing in reach.
#
# Project-specific rows (typecheck / lint / test) belong to each project: edit the PROJECT block below
# when bootstrapping. Rows that do not apply print the command that PROVES they do not apply, so
# "no target" stays a measurement rather than an assertion.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
R=prompt/maintenance/global/rules
L=prompt/maintenance/local
J="$R/common/judgment-mistakes-history.md"

n_files() { ls $1 2>/dev/null | wc -l | tr -d ' '; }
row() { printf '| %s | %s |\n' "$1" "$2"; }

echo "| Item | Measured |"
echo "|---|---|"

dirty="$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')"
row "HEAD" "\`$(git log -1 --format=%h 2>/dev/null || echo n/a)\` / uncommitted $dirty"

# --- PROJECT block: replace with this project's real gates when bootstrapping -------------------
tc="$(n_files 'tsconfig.json package.json')"
if [ "$tc" -eq 0 ]; then
  row "typecheck / lint / test" "**absence measured** (\`ls tsconfig.json package.json \\| wc -l\` = 0)"
else
  row "typecheck / lint / test" "(write this project's gates into scripts/baseline.sh)"
fi
# ------------------------------------------------------------------------------------------------

row "bug index (active)" "$(ls $L/bugs/active/*.md 2>/dev/null | grep -v index | wc -l | tr -d ' ')"
row "rules (common / local)" "$(n_files "$R/common/*.md") / $(find $L/rules -name '*.md' 2>/dev/null | wc -l | tr -d ' ')"
row "case index rows" "$(awk '/^\| case \|/{f=1;next} f&&/^\|---/{next} f&&/^\|/{n++} f&&!/^\|/{exit} END{print n+0}' "$J" 2>/dev/null)"
row "plans (active / completed)" "$(n_files "$L/plans/active/*.md") / $(n_files "$L/plans/completed/*.md")"
row "sessions recorded" "$(n_files "$L/handover/sessions/*.md")"

# The unconditional read load is a governed number (selftest B4) — surface it here so drift is visible
# at cold start rather than only when the selftest happens to be run.
#
# The unit comes from read-load.sh's own output rather than being written here. It used to be spelled
# "行" in this row while the script counted lines, and when the script's unit changed this row would
# have kept asserting the old one — a measured-number-in-prose with no update trigger (README §Single
# source of truth). Selftest B10 fails if this row stops carrying a unit. (case PT-10)
#
# The RC is taken on its own line, never through the $(...) that also carries stdout (case 82), and a
# non-zero RC produces NOT OBTAINED rather than a row built from an empty capture. A baseline row that
# silently renders "? / ?" when the instrument failed is the fail-open shape this Phase removed from
# read-load.sh itself; a consumer may not reintroduce it (rule 04 — "did not measure" is not "measured
# empty"). Since 2026-08-24 the second number is an ALLOWANCE, not a gate: size is a structure signal
# (BUDGET_STATUS), and the only failing conditions are a missing input or a broken premise.
if [ -f scripts/read-load.sh ]; then
  rl_all="$(bash scripts/read-load.sh 2>/dev/null)"
  rl_rc=$?
  if [ "$rl_rc" -ne 0 ]; then
    row "unconditional read" "**NOT OBTAINED** — \`bash scripts/read-load.sh\` exited $rl_rc (see its stderr; this is not a zero and not a small number)"
  else
    read -r rl_total rl_budget rl_unit <<<"$rl_all"
    rl_status="$(printf '%s' "$rl_all" | sed -n 's/^BUDGET_STATUS: \([A-Z_]*\).*/\1/p' | head -1)"
    rl_meas="$(printf '%s' "$rl_all" | sed -n 's/.*inputs measured \([0-9]*\/[0-9]*\).*/\1/p' | head -1)"
    row "unconditional read" "$rl_total ${rl_unit:-?} / allowance $rl_budget ${rl_unit:-?} — BUDGET_STATUS ${rl_status:-?}, inputs measured ${rl_meas:-?} (**not lines**; allowance is a signal, not a gate — breakdown and Read ranges: \`bash scripts/read-load.sh\`)"
  fi
fi

echo
echo "<!-- generated by scripts/baseline.sh — re-run, never transcribe -->"
